Traceback (most recent call last):
  File "/home/humphreyyang/miniconda3/envs/quantecon/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/humphreyyang/miniconda3/envs/quantecon/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/humphreyyang/miniconda3/envs/quantecon/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/humphreyyang/miniconda3/envs/quantecon/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/humphreyyang/miniconda3/envs/quantecon/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/humphreyyang/miniconda3/envs/quantecon/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/humphreyyang/miniconda3/envs/quantecon/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import yfinance as yf

s = yf.download('^IXIC', '2006-1-1', '2019-11-1')['Adj Close']

r = s.pct_change()

fig, ax = plt.subplots()

ax.plot(r, alpha=0.7)

ax.set_ylabel('returns', fontsize=12)
ax.set_xlabel('date', fontsize=12)

plt.show()
------------------

----- stderr -----
[*********************100%***********************]  1 of 1 completed
----- stderr -----

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mKeyError[0m                                  Traceback (most recent call last)
File [0;32m~/miniconda3/envs/quantecon/lib/python3.11/site-packages/pandas/core/indexes/base.py:3791[0m, in [0;36mIndex.get_loc[0;34m(self, key)[0m
[1;32m   3790[0m [38;5;28;01mtry[39;00m:
[0;32m-> 3791[0m     [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_engine[38;5;241m.[39mget_loc(casted_key)
[1;32m   3792[0m [38;5;28;01mexcept[39;00m [38;5;167;01mKeyError[39;00m [38;5;28;01mas[39;00m err:

File [0;32mindex.pyx:152[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32mindex.pyx:181[0m, in [0;36mpandas._libs.index.IndexEngine.get_loc[0;34m()[0m

File [0;32mpandas/_libs/hashtable_class_helper.pxi:7080[0m, in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

File [0;32mpandas/_libs/hashtable_class_helper.pxi:7088[0m, in [0;36mpandas._libs.hashtable.PyObjectHashTable.get_item[0;34m()[0m

[0;31mKeyError[0m: 'Adj Close'

The above exception was the direct cause of the following exception:

[0;31mKeyError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[4], line 3[0m
[1;32m      1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01myfinance[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01myf[39;00m
[0;32m----> 3[0m s [38;5;241m=[39m yf[38;5;241m.[39mdownload([38;5;124m'[39m[38;5;124m^IXIC[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m2006-1-1[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m2019-11-1[39m[38;5;124m'[39m)[[38;5;124m'[39m[38;5;124mAdj Close[39m[38;5;124m'[39m]
[1;32m      5[0m r [38;5;241m=[39m s[38;5;241m.[39mpct_change()
[1;32m      7[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()

File [0;32m~/miniconda3/envs/quantecon/lib/python3.11/site-packages/pandas/core/frame.py:3892[0m, in [0;36mDataFrame.__getitem__[0;34m(self, key)[0m
[1;32m   3890[0m [38;5;28;01mif[39;00m is_single_key:
[1;32m   3891[0m     [38;5;28;01mif[39;00m [38;5;28mself[39m[38;5;241m.[39mcolumns[38;5;241m.[39mnlevels [38;5;241m>[39m [38;5;241m1[39m:
[0;32m-> 3892[0m         [38;5;28;01mreturn[39;00m [38;5;28mself[39m[38;5;241m.[39m_getitem_multilevel(key)
[1;32m   3893[0m     indexer [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcolumns[38;5;241m.[39mget_loc(key)
[1;32m   3894[0m     [38;5;28;01mif[39;00m is_integer(indexer):

File [0;32m~/miniconda3/envs/quantecon/lib/python3.11/site-packages/pandas/core/frame.py:3950[0m, in [0;36mDataFrame._getitem_multilevel[0;34m(self, key)[0m
[1;32m   3948[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21m_getitem_multilevel[39m([38;5;28mself[39m, key):
[1;32m   3949[0m     [38;5;66;03m# self.columns is a MultiIndex[39;00m
[0;32m-> 3950[0m     loc [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcolumns[38;5;241m.[39mget_loc(key)
[1;32m   3951[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(loc, ([38;5;28mslice[39m, np[38;5;241m.[39mndarray)):
[1;32m   3952[0m         new_columns [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mcolumns[loc]

File [0;32m~/miniconda3/envs/quantecon/lib/python3.11/site-packages/pandas/core/indexes/multi.py:2925[0m, in [0;36mMultiIndex.get_loc[0;34m(self, key)[0m
[1;32m   2922[0m     [38;5;28;01mreturn[39;00m mask
[1;32m   2924[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(key, [38;5;28mtuple[39m):
[0;32m-> 2925[0m     loc [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_get_level_indexer(key, level[38;5;241m=[39m[38;5;241m0[39m)
[1;32m   2926[0m     [38;5;28;01mreturn[39;00m _maybe_to_slice(loc)
[1;32m   2928[0m keylen [38;5;241m=[39m [38;5;28mlen[39m(key)

File [0;32m~/miniconda3/envs/quantecon/lib/python3.11/site-packages/pandas/core/indexes/multi.py:3276[0m, in [0;36mMultiIndex._get_level_indexer[0;34m(self, key, level, indexer)[0m
[1;32m   3273[0m         [38;5;28;01mreturn[39;00m [38;5;28mslice[39m(i, j, step)
[1;32m   3275[0m [38;5;28;01melse[39;00m:
[0;32m-> 3276[0m     idx [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_get_loc_single_level_index(level_index, key)
[1;32m   3278[0m     [38;5;28;01mif[39;00m level [38;5;241m>[39m [38;5;241m0[39m [38;5;129;01mor[39;00m [38;5;28mself[39m[38;5;241m.[39m_lexsort_depth [38;5;241m==[39m [38;5;241m0[39m:
[1;32m   3279[0m         [38;5;66;03m# Desired level is not sorted[39;00m
[1;32m   3280[0m         [38;5;28;01mif[39;00m [38;5;28misinstance[39m(idx, [38;5;28mslice[39m):
[1;32m   3281[0m             [38;5;66;03m# test_get_loc_partial_timestamp_multiindex[39;00m

File [0;32m~/miniconda3/envs/quantecon/lib/python3.11/site-packages/pandas/core/indexes/multi.py:2865[0m, in [0;36mMultiIndex._get_loc_single_level_index[0;34m(self, level_index, key)[0m
[1;32m   2863[0m     [38;5;28;01mreturn[39;00m [38;5;241m-[39m[38;5;241m1[39m
[1;32m   2864[0m [38;5;28;01melse[39;00m:
[0;32m-> 2865[0m     [38;5;28;01mreturn[39;00m level_index[38;5;241m.[39mget_loc(key)

File [0;32m~/miniconda3/envs/quantecon/lib/python3.11/site-packages/pandas/core/indexes/base.py:3798[0m, in [0;36mIndex.get_loc[0;34m(self, key)[0m
[1;32m   3793[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(casted_key, [38;5;28mslice[39m) [38;5;129;01mor[39;00m (
[1;32m   3794[0m         [38;5;28misinstance[39m(casted_key, abc[38;5;241m.[39mIterable)
[1;32m   3795[0m         [38;5;129;01mand[39;00m [38;5;28many[39m([38;5;28misinstance[39m(x, [38;5;28mslice[39m) [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m casted_key)
[1;32m   3796[0m     ):
[1;32m   3797[0m         [38;5;28;01mraise[39;00m InvalidIndexError(key)
[0;32m-> 3798[0m     [38;5;28;01mraise[39;00m [38;5;167;01mKeyError[39;00m(key) [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01merr[39;00m
[1;32m   3799[0m [38;5;28;01mexcept[39;00m [38;5;167;01mTypeError[39;00m:
[1;32m   3800[0m     [38;5;66;03m# If we have a listlike key, _check_indexing_error will raise[39;00m
[1;32m   3801[0m     [38;5;66;03m#  InvalidIndexError. Otherwise we fall through and re-raise[39;00m
[1;32m   3802[0m     [38;5;66;03m#  the TypeError.[39;00m
[1;32m   3803[0m     [38;5;28mself[39m[38;5;241m.[39m_check_indexing_error(key)

[0;31mKeyError[0m: 'Adj Close'

