Traceback (most recent call last):
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cdf = np.cumsum(q_default)

@jit(nopython=True)
def compute_stopping_time(w_bar, seed=1234):

    np.random.seed(seed)
    t = 1
    while True:
        # Generate a wage draw
        w = w_default[qe.random.draw(cdf)]
        # Stop when the draw is above the reservation wage
        if w >= w_bar:
            stopping_time = t
            break
        else:
            t += 1
    return stopping_time

@jit(nopython=True)
def compute_mean_stopping_time(w_bar, num_reps=100000):
    obs = np.empty(num_reps)
    for i in range(num_reps):
        obs[i] = compute_stopping_time(w_bar, seed=i)
    return obs.mean()

c_vals = np.linspace(10, 40, 25)
stop_times = np.empty_like(c_vals)
for i, c in enumerate(c_vals):
    mcm = McCallModel(c=c)
    w_bar = compute_reservation_wage_two(mcm)
    stop_times[i] = compute_mean_stopping_time(w_bar)

fig, ax = plt.subplots()

ax.plot(c_vals, stop_times, label="mean unemployment duration")
ax.set(xlabel="unemployment compensation", ylabel="months")
ax.legend()

plt.show()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypingError[0m                               Traceback (most recent call last)
Cell [0;32mIn[15], line 31[0m
[1;32m     29[0m     mcm [38;5;241m=[39m McCallModel(c[38;5;241m=[39mc)
[1;32m     30[0m     w_bar [38;5;241m=[39m compute_reservation_wage_two(mcm)
[0;32m---> 31[0m     stop_times[i] [38;5;241m=[39m [43mcompute_mean_stopping_time[49m[43m([49m[43mw_bar[49m[43m)[49m
[1;32m     33[0m fig, ax [38;5;241m=[39m plt[38;5;241m.[39msubplots()
[1;32m     35[0m ax[38;5;241m.[39mplot(c_vals, stop_times, label[38;5;241m=[39m[38;5;124m"[39m[38;5;124mmean unemployment duration[39m[38;5;124m"[39m)

File [0;32m~/anaconda3/envs/quantecon/lib/python3.9/site-packages/numba/core/dispatcher.py:468[0m, in [0;36m_DispatcherBase._compile_for_args[0;34m(self, *args, **kws)[0m
[1;32m    464[0m         msg [38;5;241m=[39m ([38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;28mstr[39m(e)[38;5;241m.[39mrstrip()[38;5;132;01m}[39;00m[38;5;124m [39m[38;5;130;01m\n[39;00m[38;5;130;01m\n[39;00m[38;5;124mThis error may have been caused [39m[38;5;124m"[39m
[1;32m    465[0m                [38;5;124mf[39m[38;5;124m"[39m[38;5;124mby the following argument(s):[39m[38;5;130;01m\n[39;00m[38;5;132;01m{[39;00margs_str[38;5;132;01m}[39;00m[38;5;130;01m\n[39;00m[38;5;124m"[39m)
[1;32m    466[0m         e[38;5;241m.[39mpatch_message(msg)
[0;32m--> 468[0m     [43merror_rewrite[49m[43m([49m[43me[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mtyping[39;49m[38;5;124;43m'[39;49m[43m)[49m
[1;32m    469[0m [38;5;28;01mexcept[39;00m errors[38;5;241m.[39mUnsupportedError [38;5;28;01mas[39;00m e:
[1;32m    470[0m     [38;5;66;03m# Something unsupported is present in the user code, add help info[39;00m
[1;32m    471[0m     error_rewrite(e, [38;5;124m'[39m[38;5;124munsupported_error[39m[38;5;124m'[39m)

File [0;32m~/anaconda3/envs/quantecon/lib/python3.9/site-packages/numba/core/dispatcher.py:409[0m, in [0;36m_DispatcherBase._compile_for_args.<locals>.error_rewrite[0;34m(e, issue_type)[0m
[1;32m    407[0m     [38;5;28;01mraise[39;00m e
[1;32m    408[0m [38;5;28;01melse[39;00m:
[0;32m--> 409[0m     [38;5;28;01mraise[39;00m e[38;5;241m.[39mwith_traceback([38;5;28;01mNone[39;00m)

[0;31mTypingError[0m: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1m[1mFailed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mNo implementation of function Function(<function draw at 0x117f6e5e0>) found for signature:
 
 >>> draw(readonly array(float64, 1d, C))
 
There are 2 candidate implementations:
[1m   - Of which 2 did not match due to:
   Overload in function 'ol_draw': File: quantecon/random/utilities.py: Line 213.
     With argument(s): '(readonly array(float64, 1d, C))':[0m
[1m    Rejected as the implementation raised a specific error:
      TypingError: [1mmissing a required argument: 'size'[0m[0m
  raised from /Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/numba/core/typing/templates.py:784
[0m
[0m[1mDuring: resolving callee type: Function(<function draw at 0x117f6e5e0>)[0m
[0m[1mDuring: typing of call at /var/folders/91/qcgtwcq13wn4fz1gvycjhd0w0000gn/T/ipykernel_80495/474854781.py (10)
[0m
[1m
File "../../../../../../../var/folders/91/qcgtwcq13wn4fz1gvycjhd0w0000gn/T/ipykernel_80495/474854781.py", line 10:[0m
[1m<source missing, REPL/exec in use?>[0m

[0m[1mDuring: resolving callee type: type(CPUDispatcher(<function compute_stopping_time at 0x154b1c670>))[0m
[0m[1mDuring: typing of call at /var/folders/91/qcgtwcq13wn4fz1gvycjhd0w0000gn/T/ipykernel_80495/474854781.py (23)
[0m
[0m[1mDuring: resolving callee type: type(CPUDispatcher(<function compute_stopping_time at 0x154b1c670>))[0m
[0m[1mDuring: typing of call at /var/folders/91/qcgtwcq13wn4fz1gvycjhd0w0000gn/T/ipykernel_80495/474854781.py (23)
[0m
[1m
File "../../../../../../../var/folders/91/qcgtwcq13wn4fz1gvycjhd0w0000gn/T/ipykernel_80495/474854781.py", line 23:[0m
[1m<source missing, REPL/exec in use?>[0m

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1m[1mFailed in nopython mode pipeline (step: nopython frontend)
[1m[1m[1mNo implementation of function Function(<function draw at 0x117f6e5e0>) found for signature:
 
 >>> draw(readonly array(float64, 1d, C))
 
There are 2 candidate implementations:
[1m   - Of which 2 did not match due to:
   Overload in function 'ol_draw': File: quantecon/random/utilities.py: Line 213.
     With argument(s): '(readonly array(float64, 1d, C))':[0m
[1m    Rejected as the implementation raised a specific error:
      TypingError: [1mmissing a required argument: 'size'[0m[0m
  raised from /Users/humphreyyang/anaconda3/envs/quantecon/lib/python3.9/site-packages/numba/core/typing/templates.py:784
[0m
[0m[1mDuring: resolving callee type: Function(<function draw at 0x117f6e5e0>)[0m
[0m[1mDuring: typing of call at /var/folders/91/qcgtwcq13wn4fz1gvycjhd0w0000gn/T/ipykernel_80495/474854781.py (10)
[0m
[1m
File "../../../../../../../var/folders/91/qcgtwcq13wn4fz1gvycjhd0w0000gn/T/ipykernel_80495/474854781.py", line 10:[0m
[1m<source missing, REPL/exec in use?>[0m

[0m[1mDuring: resolving callee type: type(CPUDispatcher(<function compute_stopping_time at 0x154b1c670>))[0m
[0m[1mDuring: typing of call at /var/folders/91/qcgtwcq13wn4fz1gvycjhd0w0000gn/T/ipykernel_80495/474854781.py (23)
[0m
[0m[1mDuring: resolving callee type: type(CPUDispatcher(<function compute_stopping_time at 0x154b1c670>))[0m
[0m[1mDuring: typing of call at /var/folders/91/qcgtwcq13wn4fz1gvycjhd0w0000gn/T/ipykernel_80495/474854781.py (23)
[0m
[1m
File "../../../../../../../var/folders/91/qcgtwcq13wn4fz1gvycjhd0w0000gn/T/ipykernel_80495/474854781.py", line 23:[0m
[1m<source missing, REPL/exec in use?>[0m


